import Helmet from "react-helmet";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import How from "../components/How";
import Footer from "../components/Footer";
import ScrollToTop from "../components/ScrollToTop";
import Features from "../components/Features";
import Cta from "../components/Cta";
import { useEffect } from "react";
import axios from "axios";

export default function Home() {
  useEffect(() => {
    axios.get("/api").then(({data}) => {
      console.log(data)
    });
  }, []);

  return (
    <>
      <Helmet>
        <title>Resume Builder - By Roqeeb</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Helmet>

      <main>
        <ScrollToTop />
        <Navbar />
        <Hero />
        <Features />
        <How />
        <Cta />
        <Footer />
      </main>
    </>
  );
}
